INSERT INTO employee(id, first_name, last_name) VALUES (1,'Derrick', 'Stewart');
INSERT INTO employee(id, first_name, last_name) VALUES (2,'Janice', 'Ferguson');

INSERT INTO department(id, code, name) VALUES (1,'department_1', 'ADELAIDE');
INSERT INTO department(id, code, name) VALUES (2,'department_2', 'BEEF BUYERS');
INSERT INTO department(id, code, name) VALUES (3,'department_3', 'BEEF CITY');
INSERT INTO department(id, code, name) VALUES (4,'department_4', 'BORDERTOWN');
INSERT INTO department(id, code, name) VALUES (5,'department_5', 'BRISBANE');
INSERT INTO department(id, code, name) VALUES (6,'department_6', 'BROOKLYN');
INSERT INTO department(id, code, name) VALUES (7,'department_7', 'CHULORA');
INSERT INTO department(id, code, name) VALUES (8,'department_8', 'COBRAM');
INSERT INTO department(id, code, name) VALUES (9,'department_9', 'DEVELOPMENT');
INSERT INTO department(id, code, name) VALUES (10,'department_10', 'DEVONPORT');
INSERT INTO department(id, code, name) VALUES (11,'department_11', 'DINMORE');
INSERT INTO department(id, code, name) VALUES (12,'department_12', 'FOODPARTNERS');
INSERT INTO department(id, code, name) VALUES (13,'department_13', 'HELP DESK');
INSERT INTO department(id, code, name) VALUES (14,'department_14', 'HR SYSTEMS');
INSERT INTO department(id, code, name) VALUES (15,'department_15', 'INFRASTRUCTURE');
INSERT INTO department(id, code, name) VALUES (16,'department_16', 'INTERNAL AUDIT');
INSERT INTO department(id, code, name) VALUES (17,'department_17', 'JOES SITES');
INSERT INTO department(id, code, name) VALUES (18,'department_18', 'LEGAL');
INSERT INTO department(id, code, name) VALUES (19,'department_19', 'LONGFORD');
INSERT INTO department(id, code, name) VALUES (20,'department_20', 'MAN ACCOUNTING');
INSERT INTO department(id, code, name) VALUES (21,'department_21', 'MELBOURNE');
INSERT INTO department(id, code, name) VALUES (22,'department_22', 'MUGINDI');
INSERT INTO department(id, code, name) VALUES (23,'department_23', 'OHS');
INSERT INTO department(id, code, name) VALUES (24,'department_24', 'OPS AND PROCESSES');
INSERT INTO department(id, code, name) VALUES (25,'department_25', 'PAYROLL');
INSERT INTO department(id, code, name) VALUES (26,'department_26', 'PERTH');
INSERT INTO department(id, code, name) VALUES (27,'department_27', 'PORT WAKEFIELD');
INSERT INTO department(id, code, name) VALUES (28,'department_28', 'PRIME CITY');
INSERT INTO department(id, code, name) VALUES (29,'department_29', 'PRODUCTION STREET');
INSERT INTO department(id, code, name) VALUES (30,'department_30', 'REG AND PUBLIC AFFAIRS');
INSERT INTO department(id, code, name) VALUES (31,'department_31', 'RIVERINA');
INSERT INTO department(id, code, name) VALUES (32,'department_32', 'ROCKHAMPTON');
INSERT INTO department(id, code, name) VALUES (33,'department_33', 'SCONE');
INSERT INTO department(id, code, name) VALUES (34,'department_34', 'SHEEP BUYERS');
INSERT INTO department(id, code, name) VALUES (35,'department_35', 'SHIPPING');
INSERT INTO department(id, code, name) VALUES (36,'department_36', 'SYDNEY');
INSERT INTO department(id, code, name) VALUES (37,'department_37', 'TASMANIA');
INSERT INTO department(id, code, name) VALUES (38,'department_38', 'TOWNSVILLE');
INSERT INTO department(id, code, name) VALUES (39,'department_39', 'TRADING');
INSERT INTO department(id, code, name) VALUES (40,'department_40', 'TRAINING');
INSERT INTO department(id, code, name) VALUES (41,'department_41', 'TREASURY');
INSERT INTO department(id, code, name) VALUES (42,'department_42', 'WACOL');
INSERT INTO department(id, code, name) VALUES (43,'department_43', 'WORKERS COMP');

INSERT INTO section(id, code, name) VALUES (1,'section_1', 'BACON');
INSERT INTO section(id, code, name) VALUES (2,'section_2', 'BONING ROOM');
INSERT INTO section(id, code, name) VALUES (3,'section_3', 'BONING ROOM - BEEF');
INSERT INTO section(id, code, name) VALUES (4,'section_4', 'BONING ROOM - SHEEP');
INSERT INTO section(id, code, name) VALUES (5,'section_5', 'COLD STORES');
INSERT INTO section(id, code, name) VALUES (6,'section_6', 'ENGINEERING OPERATIONS');
INSERT INTO section(id, code, name) VALUES (7,'section_7', 'ENVIRONMENT');
INSERT INTO section(id, code, name) VALUES (8,'section_8', 'FINANCE & ADMINISTRATION');
INSERT INTO section(id, code, name) VALUES (9,'section_9', 'FSQA');
INSERT INTO section(id, code, name) VALUES (10,'section_10', 'HAM');
INSERT INTO section(id, code, name) VALUES (11,'section_11', 'HIDES');
INSERT INTO section(id, code, name) VALUES (12,'section_12', 'HR OPERATIONS');
INSERT INTO section(id, code, name) VALUES (13,'section_13', 'KILL FLOOR');
INSERT INTO section(id, code, name) VALUES (14,'section_14', 'KILL FLOOR - BEEF');
INSERT INTO section(id, code, name) VALUES (15,'section_15', 'KILL FLOOR - SHEEP');
INSERT INTO section(id, code, name) VALUES (16,'section_16', 'LOADOUT');
INSERT INTO section(id, code, name) VALUES (17,'section_17', 'OFFAL');
INSERT INTO section(id, code, name) VALUES (18,'section_18', 'PRODUCTION CONTROL');
INSERT INTO section(id, code, name) VALUES (19,'section_19', 'PURCHASING');
INSERT INTO section(id, code, name) VALUES (20,'section_20', 'RENDERING');
INSERT INTO section(id, code, name) VALUES (21,'section_21', 'SAFETY');
INSERT INTO section(id, code, name) VALUES (22,'section_22', 'SALAMI');
INSERT INTO section(id, code, name) VALUES (23,'section_23', 'SALES');
INSERT INTO section(id, code, name) VALUES (24,'section_24', 'TRANSPORT & LOGISTICS');
INSERT INTO section(id, code, name) VALUES (25,'section_25', 'VALUE ADDED');
INSERT INTO section(id, code, name) VALUES (26,'section_26', 'WAREHOUSE & DISTRIBUTION');

INSERT INTO shift(id, code, name) VALUES (1,'shift_1', 'Day Shift');
INSERT INTO shift(id, code, name) VALUES (2,'shift_2', 'Afternoon Shift');
INSERT INTO shift(id, code, name) VALUES (3,'shift_3', 'Night Shift');